trigger: none

variables:
  - template: ../../eng/pipelines/templates/variables/globals.yml
  - name: AdditionalArgs
    value: ''

stages:
  - ${{ if or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest')) }}:
    - template: /sdk/cosmos/ci.spark.databricks.yml
      parameters:
        CosmosEndpoint: $(spark-databricks-cosmos-endpoint)
        CosmosKey: $(spark-databricks-cosmos-key)
        DatabricksEndpoint: $(spark-databricks-endpoint)
        DatabricksToken: $(spark-databricks-token)
